dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.6.15
  - ld_impl_linux-64=2.43
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgomp=15.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libsqlite=3.50.2
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.0
  - pip=25.1.1
  - python=3.9.23
  - python_abi=3.9
  - readline=8.2
  - setuptools=59.8.0
  - tk=8.6.13
  - wheel=0.45.1
  - pip:
      - alabaster==0.7.16
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.0
      - argparse==1.4.0
      - asciitree==0.3.3
      - asttokens==3.0.0
      - autograd==1.8.0
      - babel==2.17.0
      - certifi==2025.6.15
      - charset-normalizer==3.4.2
      - click==8.1.8
      - comm==0.2.2
      - contourpy==1.3.0
      - cooler==0.10.3
      - cycler==0.12.1
      - cytoolz==1.0.1
      - debugpy==1.8.14
      - decorator==5.2.1
      - dill==0.4.0
      - docutils==0.21.2
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - fastapi==0.124.0
      - fonttools==4.58.4
      - h11==0.16.0
      - h5py==3.14.0
      - hic-straw==1.3.1
      - httptools==0.7.1
      - iced==0.6.0
      - idna==3.10
      - imagesize==1.4.1
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - ipykernel==6.29.5
      - ipython==8.18.1
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - kiwisolver==1.4.7
      - markupsafe==3.0.2
      - matplotlib==3.9.4
      - matplotlib-inline==0.1.7
      - multiprocess==0.70.18
      - natsort==8.4.0
      - ncls==0.0.70
      - nest-asyncio==1.6.0
      - nose==1.3.7
      - numpy==2.0.2
      - numpydoc==1.9.0
      - packaging==25.0
      - pandas==2.3.0
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.2.1
      - platformdirs==4.3.8
      - pluggy==1.6.0
      - prompt-toolkit==3.0.51
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pybind11==3.0.1
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyfaidx==0.8.1.4
      - pygments==2.19.2
      - pyparsing==3.2.3
      - pyranges==0.1.4
      - pytest==8.4.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==27.0.0
      - requests==2.32.4
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - simplejson==3.20.1
      - six==1.17.0
      - snowballstemmer==3.0.1
      - sorted-nearest==0.0.41
      - sphinx==7.4.7
      - sphinx-gallery==0.19.0
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - stack-data==0.6.3
      - starlette==0.49.3
      - tabulate==0.9.0
      - threadpoolctl==3.6.0
      - tomli==2.2.1
      - toolz==1.0.0
      - tornado==6.5.1
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - utils==1.0.2
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - watchfiles==1.1.1
      - wcwidth==0.2.13
      - websockets==15.0.1
      - zipp==3.23.0
